version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8004
    volumes: 
      - './app:/usr/src/app'
    ports:
      - "8004:8004"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment: 
      MYSQL_NAME: django_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
  db:
    build: ./mysql
    volumes: 
      - ./db:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: django_development
      MYSQL_ROOT_PASSWORD: password
    env_file:
      - ./.env
    ports:
      - "3306:3306"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   # env_file:
  #   #   - .env.dev
  #   links:
  #     - db
  #   ports:
  #     - "4000:80"
  #   volumes:
  #     - ./phpmyadmin/sessions:/sessions
  #   # networks:
  #   #   - fastapi_network
  #   environment:
  #     PMA_ARBITRARY: 1
  #     PMA_HOST: db
  #     PMA_USER: root
  #     PMA_PASSWORD: password
