version: '3'

services:
  web:
    image: 197136345155.dkr.ecr.ap-northeast-1.amazonaws.com/django-ecs-sample-web0317:latest
    command: sh ./run-my-app.sh
    volumes: 
      - './app:/usr/src/app'
    ports:
      - "8004:8004"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment: 
      MYSQL_NAME: django_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
  db:
    image: 197136345155.dkr.ecr.ap-northeast-1.amazonaws.com/django-ecs-sample-mysql0317:latest
    volumes: 
      - ./db:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: django_development
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

