# Generated by Django 3.2 on 2022-03-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_word', '0002_auto_20220309_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cross_wordSomething',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crossword_id', models.IntegerField(default=-1)),
                ('crossword_ans', models.CharField(max_length=500)),
                ('crossword_ans_comment', models.CharField(max_length=500)),
                ('crossword_js', models.CharField(max_length=500)),
            ],
        ),
    ]
